"use client";

import { TeamPlayer, TeamRoster } from "./gd-roster";

const players: TeamPlayer[] = [
  { id: "gs-54", number: "54", name: "강로건", position: "투수", grade: "3학년", height: 190, weight: 97, batsThrows: "좌투좌타" },
  { id: "gs-24", number: "24", name: "강우진", position: "내야수", grade: "1학년", height: 170, weight: 65, batsThrows: "우투우타" },
  { id: "gs-18", number: "18", name: "고경민", position: "투수", grade: "3학년", height: 182, weight: 87, batsThrows: "우투우타" },
  { id: "gs-gujunmo", number: "—", name: "구준모", position: "투수", grade: "1학년", height: 178, weight: 80, batsThrows: "우투우타" },
  { id: "gs-12", number: "12", name: "길호형", position: "투수", grade: "1학년", height: 174, weight: 76, batsThrows: "우투좌타" },
  { id: "gs-56", number: "56", name: "김건종", position: "포수", grade: "1학년", height: 180, weight: 78, batsThrows: "우투우타" },
  { id: "gs-55", number: "55", name: "김도담", position: "투수", grade: "1학년", height: 185, weight: 85, batsThrows: "우투우타" },
  { id: "gs-3", number: "3", name: "김동건", position: "내야수", grade: "3학년", height: 177, weight: 78, batsThrows: "우투좌타" },
  { id: "gs-21", number: "21", name: "김민규", position: "투수", grade: "3학년", height: 184, weight: 87, batsThrows: "우투우타" },
  { id: "gs-41", number: "41", name: "김민재", position: "투수", grade: "3학년", height: 187, weight: 95, batsThrows: "우투우타" },
  { id: "gs-7", number: "7", name: "김승원", position: "외야수", grade: "3학년", height: 179, weight: 76, batsThrows: "우투우타" },
  { id: "gs-49", number: "49", name: "김시현", position: "투수", grade: "2학년", height: 184, weight: 88, batsThrows: "우투우타" },
  { id: "gs-50", number: "50", name: "김지후", position: "투수", grade: "1학년", height: 180, weight: 70, batsThrows: "우투우타" },
  { id: "gs-22", number: "22", name: "남궁승준", position: "외야수", grade: "1학년", height: 177, weight: 85, batsThrows: "좌투좌타" },
  { id: "gs-20", number: "20", name: "노영진", position: "투수", grade: "2학년", height: 175, weight: 77, batsThrows: "우투우타" },
  { id: "gs-43", number: "43", name: "박성철", position: "투수", grade: "1학년", height: 181, weight: 88, batsThrows: "우투우타" },
  { id: "gs-5", number: "5", name: "박성현", position: "내야수", grade: "3학년", height: 183, weight: 76, batsThrows: "우투우타" },
  { id: "gs-32", number: "32", name: "박성훈", position: "내야수", grade: "1학년", height: 175, weight: 60, batsThrows: "우투좌타" },
  { id: "gs-6", number: "6", name: "박인효", position: "외야수", grade: "3학년", height: 179, weight: 81, batsThrows: "좌투좌타" },
  { id: "gs-25", number: "25", name: "백찬영", position: "투수", grade: "2학년", height: 187, weight: 86, batsThrows: "우투우타" },
  { id: "gs-seokjunho", number: "—", name: "석준호", position: "투수", grade: "1학년", height: 186, weight: 88, batsThrows: "우투우타" },
  { id: "gs-14", number: "14", name: "신지호", position: "투수", grade: "1학년", height: 185, weight: 85, batsThrows: "우투우타" },
  { id: "gs-51", number: "51", name: "안정민", position: "외야수", grade: "2학년", height: 184, weight: 84, batsThrows: "우투좌타" },
  { id: "gs-antaeuk", number: "—", name: "안태욱", position: "내야수", grade: "2학년", height: 175, weight: 71, batsThrows: "우투우타" },
  { id: "gs-46", number: "46", name: "양승우", position: "투수", grade: "1학년", height: 179, weight: 75, batsThrows: "우투우타" },
  { id: "gs-19", number: "19", name: "오혜찬", position: "투수", grade: "3학년", height: 190, weight: 90, batsThrows: "우투우타" },
  { id: "gs-23", number: "23", name: "원현종", position: "투수", grade: "1학년", height: 185, weight: 82, batsThrows: "우투우타" },
  { id: "gs-15", number: "15", name: "유동균", position: "투수", grade: "3학년", height: 186, weight: 90, batsThrows: "좌투좌타" },
  { id: "gs-38", number: "38", name: "윤태경", position: "투수", grade: "1학년", height: 180, weight: 87, batsThrows: "우투우타" },
  { id: "gs-1", number: "1", name: "이건", position: "투수", grade: "1학년", height: 184, weight: 82, batsThrows: "우투양타" },
  { id: "gs-42", number: "42", name: "이동경", position: "포수", grade: "2학년", height: 181, weight: 84, batsThrows: "우투우타" },
  { id: "gs-16", number: "16", name: "이동훈", position: "내야수", grade: "2학년", height: 184, weight: 83, batsThrows: "우투좌타" },
  { id: "gs-29", number: "29", name: "이서윤", position: "투수", grade: "2학년", height: 182, weight: 80, batsThrows: "좌투좌타" },
  { id: "gs-36", number: "36", name: "이선율", position: "외야수", grade: "1학년", height: 173, weight: 72, batsThrows: "우투좌타" },
  { id: "gs-61", number: "61", name: "이승민", position: "투수", grade: "2학년", height: 184, weight: 87, batsThrows: "우투우타" },
  { id: "gs-10", number: "10", name: "이준우", position: "내야수", grade: "2학년", height: 182, weight: 82, batsThrows: "우투우타" },
  { id: "gs-37", number: "37", name: "이준혁", position: "내야수", grade: "1학년", height: 175, weight: 70, batsThrows: "우투우타" },
  { id: "gs-26", number: "26", name: "이지호", position: "투수", grade: "1학년", height: 182, weight: 72, batsThrows: "우투우타" },
  { id: "gs-31", number: "31", name: "전지율", position: "외야수", grade: "1학년", height: 178, weight: 78, batsThrows: "좌투좌타" },
  { id: "gs-17", number: "17", name: "정우영", position: "투수", grade: "1학년", height: 180, weight: 80, batsThrows: "좌투좌타" },
  { id: "gs-30", number: "30", name: "정윤우", position: "내야수", grade: "1학년", height: 185, weight: 80, batsThrows: "우투좌타" },
  { id: "gs-35", number: "35", name: "정이준", position: "포수", grade: "1학년", height: 178, weight: 90, batsThrows: "우투좌타" },
  { id: "gs-44", number: "44", name: "정지우", position: "내야수", grade: "1학년", height: 172, weight: 74, batsThrows: "우투좌타" },
  { id: "gs-13", number: "13", name: "정해성", position: "외야수", grade: "2학년", height: 181, weight: 82, batsThrows: "우투우타" },
  { id: "gs-9", number: "9", name: "정희율", position: "내야수", grade: "1학년", height: 175, weight: 70, batsThrows: "우투좌타" },
  { id: "gs-11", number: "11", name: "조현민", position: "투수", grade: "2학년", height: 186, weight: 82, batsThrows: "우투좌타" },
  { id: "gs-47", number: "47", name: "주민혁", position: "포수", grade: "2학년", height: 184, weight: 84, batsThrows: "우투우타" },
  { id: "gs-4", number: "4", name: "주하율", position: "내야수", grade: "1학년", height: 177, weight: 68, batsThrows: "우투우타" },
  { id: "gs-8", number: "8", name: "지호영", position: "외야수", grade: "3학년", height: 180, weight: 83, batsThrows: "우투우타" },
  { id: "gs-33", number: "33", name: "최승호", position: "외야수", grade: "1학년", height: 183, weight: 72, batsThrows: "좌투좌타" },
  { id: "gs-27", number: "27", name: "최연수", position: "포수", grade: "1학년", height: 179, weight: 80, batsThrows: "우투우타" },
  { id: "gs-45", number: "45", name: "최은혁", position: "투수", grade: "1학년", height: 185, weight: 75, batsThrows: "좌투좌타" },
  { id: "gs-52", number: "52", name: "홍민준", position: "내야수", grade: "1학년", height: 180, weight: 66, batsThrows: "우투우타" },
];

export default function GyeongsangRoster() {
  return <TeamRoster sectionId="gyeongsang-roster" kicker="GYEONGGI COMMERCIAL HIGH SCHOOL · U-18" title="경기상업고 선수단" subtitle="2026 등록 선수 53명 · 감독 최덕현" teamLabel="경기상업고" monogram="GS" players={players} />;
}
