"use client";

import { TeamPlayer, TeamRoster } from "./gd-roster";

const players: TeamPlayer[] = [
  { id: "gg-49", number: "49", name: "강지호", position: "투수", grade: "1학년", height: 175, weight: 78, batsThrows: "우투우타" },
  { id: "gg-9", number: "9", name: "강태환", position: "투수", grade: "2학년", height: 182, weight: 89, batsThrows: "좌투좌타" },
  { id: "gg-38", number: "38", name: "고준서", position: "투수", grade: "2학년", height: 181, weight: 85, batsThrows: "좌투좌타" },
  { id: "gg-55", number: "55", name: "김대우", position: "투수", grade: "3학년", height: 178, weight: 80, batsThrows: "우투우타" },
  { id: "gg-16", number: "16", name: "김대현", position: "내야수", grade: "3학년", height: 183, weight: 85, batsThrows: "우투좌타" },
  { id: "gg-6", number: "6", name: "김민성", position: "내야수", grade: "2학년", height: 180, weight: 76, batsThrows: "우투우타" },
  { id: "gg-54", number: "54", name: "김범준", position: "외야수", grade: "1학년", height: 184, weight: 85, batsThrows: "우투우타" },
  { id: "gg-48", number: "48", name: "김성찬", position: "외야수", grade: "1학년", height: 170, weight: 67, batsThrows: "우투우타" },
  { id: "gg-69", number: "69", name: "김성훈", position: "투수", grade: "3학년", height: 181, weight: 97, batsThrows: "우투좌타" },
  { id: "gg-40", number: "40", name: "김시온", position: "투수", grade: "3학년", height: 190, weight: 110, batsThrows: "우투우타" },
  { id: "gg-30", number: "30", name: "김요섭", position: "내야수", grade: "1학년", height: 183, weight: 72, batsThrows: "우투좌타" },
  { id: "gg-42", number: "42", name: "김유환", position: "포수", grade: "1학년", height: 178, weight: 81, batsThrows: "우투좌타" },
  { id: "gg-3", number: "3", name: "김재우", position: "외야수", grade: "1학년", height: 178, weight: 78, batsThrows: "우투좌타" },
  { id: "gg-59", number: "59", name: "김주원", position: "투수", grade: "1학년", height: 185, weight: 83, batsThrows: "우투좌타" },
  { id: "gg-43", number: "43", name: "김지환", position: "내야수", grade: "1학년", height: 171, weight: 68, batsThrows: "우투우타" },
  { id: "gg-17", number: "17", name: "김태윤", position: "투수", grade: "3학년", height: 185, weight: 84, batsThrows: "우투우타" },
  { id: "gg-36", number: "36", name: "김태희", position: "투수", grade: "1학년", height: 177, weight: 86, batsThrows: "우투우타" },
  { id: "gg-50", number: "50", name: "김하준", position: "내야수", grade: "1학년", height: 180, weight: 87, batsThrows: "우투우타" },
  { id: "gg-39", number: "39", name: "나시영", position: "투수", grade: "2학년", height: 183, weight: 85, batsThrows: "우투우타" },
  { id: "gg-21", number: "21", name: "남궁민", position: "투수", grade: "3학년", height: 178, weight: 80, batsThrows: "우투우타" },
  { id: "gg-31", number: "31", name: "류승열", position: "외야수", grade: "3학년", height: 165, weight: 56, batsThrows: "좌투좌타" },
  { id: "gg-46", number: "46", name: "민경준", position: "외야수", grade: "1학년", height: 173, weight: 64, batsThrows: "우투우타" },
  { id: "gg-8", number: "8", name: "박건우", position: "외야수", grade: "1학년", height: 173, weight: 60, batsThrows: "우투우타" },
  { id: "gg-51", number: "51", name: "박두이", position: "외야수", grade: "3학년", height: 178, weight: 78, batsThrows: "우투우타" },
  { id: "gg-19", number: "19", name: "박성준", position: "투수", grade: "3학년", height: 180, weight: 65, batsThrows: "우투우타" },
  { id: "gg-15", number: "15", name: "박승원", position: "투수", grade: "3학년", height: 183, weight: 85, batsThrows: "우투우타" },
  { id: "gg-13", number: "13", name: "박준우", position: "투수", grade: "2학년", height: 179, weight: 70, batsThrows: "우투우타" },
  { id: "gg-35", number: "35", name: "배서준", position: "내야수", grade: "1학년", height: 181, weight: 81, batsThrows: "우투우타" },
  { id: "gg-seogwangeun", number: "—", name: "서광은", position: "투수", grade: "1학년", height: 178, weight: 70, batsThrows: "우투우타" },
  { id: "gg-18", number: "18", name: "서준호", position: "투수", grade: "3학년", height: 183, weight: 82, batsThrows: "우투우타" },
  { id: "gg-10", number: "10", name: "송무경", position: "내야수", grade: "3학년", height: 181, weight: 86, batsThrows: "우투우타" },
  { id: "gg-1", number: "1", name: "송윤상", position: "투수", grade: "3학년", height: 196, weight: 98, batsThrows: "우투우타" },
  { id: "gg-14", number: "14", name: "신율", position: "투수", grade: "1학년", height: 178, weight: 73, batsThrows: "우투우타" },
  { id: "gg-32", number: "32", name: "신정우", position: "투수", grade: "2학년", height: 181, weight: 78, batsThrows: "우투우타" },
  { id: "gg-41", number: "41", name: "신현호", position: "투수", grade: "3학년", height: 186, weight: 84, batsThrows: "우투우타" },
  { id: "gg-5", number: "5", name: "신희수", position: "투수", grade: "2학년", height: 178, weight: 75, batsThrows: "좌투좌타" },
  { id: "gg-37", number: "37", name: "안승연", position: "외야수", grade: "3학년", height: 183, weight: 85, batsThrows: "우투우타" },
  { id: "gg-57", number: "57", name: "안준서", position: "투수", grade: "2학년", height: 179, weight: 77, batsThrows: "우투우타" },
  { id: "gg-11", number: "11", name: "양인성", position: "투수", grade: "3학년", height: 187, weight: 90, batsThrows: "우투좌타" },
  { id: "gg-27", number: "27", name: "양종현", position: "포수", grade: "3학년", height: 180, weight: 85, batsThrows: "우투우타" },
  { id: "gg-7", number: "7", name: "엄찬혁", position: "내야수", grade: "3학년", height: 186, weight: 81, batsThrows: "우투우타" },
  { id: "gg-24", number: "24", name: "오준영", position: "내야수", grade: "3학년", height: 176, weight: 85, batsThrows: "우투우타" },
  { id: "gg-44", number: "44", name: "유동현", position: "내야수", grade: "1학년", height: 178, weight: 77, batsThrows: "우투좌타" },
  { id: "gg-33", number: "33", name: "이민찬", position: "투수", grade: "2학년", height: 182, weight: 76, batsThrows: "우투좌타" },
  { id: "gg-65", number: "65", name: "이승규", position: "외야수", grade: "2학년", height: 180, weight: 80, batsThrows: "우투우타" },
  { id: "gg-2", number: "2", name: "이유진", position: "포수", grade: "2학년", height: 182, weight: 85, batsThrows: "우투우타" },
  { id: "gg-28", number: "28", name: "이준민", position: "투수", grade: "1학년", height: 178, weight: 70, batsThrows: "우투우타" },
  { id: "gg-61", number: "61", name: "이진형", position: "투수", grade: "2학년", height: 183, weight: 87, batsThrows: "우투좌타" },
  { id: "gg-22", number: "22", name: "이하준", position: "투수", grade: "2학년", height: 183, weight: 85, batsThrows: "우투우타" },
  { id: "gg-12", number: "12", name: "이후서", position: "투수", grade: "3학년", height: 182, weight: 82, batsThrows: "우투우타" },
  { id: "gg-60", number: "60", name: "장혁", position: "투수", grade: "2학년", height: 183, weight: 90, batsThrows: "우투우타" },
  { id: "gg-25", number: "25", name: "전기상", position: "포수", grade: "1학년", height: 180, weight: 86, batsThrows: "우투우타" },
  { id: "gg-45", number: "45", name: "전지원", position: "투수", grade: "1학년", height: 185, weight: 83, batsThrows: "우투우타" },
  { id: "gg-26", number: "26", name: "전하준", position: "외야수", grade: "2학년", height: 174, weight: 83, batsThrows: "우투우타" },
  { id: "gg-4", number: "4", name: "정지우", position: "포수", grade: "2학년", height: 180, weight: 77, batsThrows: "우투우타" },
  { id: "gg-23", number: "23", name: "정진명", position: "외야수", grade: "2학년", height: 186, weight: 90, batsThrows: "우투우타" },
  { id: "gg-47", number: "47", name: "조용준", position: "외야수", grade: "1학년", height: 183, weight: 83, batsThrows: "우투우타" },
  { id: "gg-34", number: "34", name: "최유진", position: "외야수", grade: "1학년", height: 180, weight: 77, batsThrows: "좌투좌타" },
  { id: "gg-52", number: "52", name: "최지안", position: "외야수", grade: "3학년", height: 186, weight: 95, batsThrows: "우투우타" },
  { id: "gg-29", number: "29", name: "편경제", position: "투수", grade: "2학년", height: 185, weight: 94, batsThrows: "우투우타" },
];

export default function GyeonggiRoster() {
  return <TeamRoster sectionId="gyeonggi-roster" kicker="GYEONGGI HIGH SCHOOL · U-18" title="경기고 선수단" subtitle="2026 등록 선수 60명 · 감독 오규택" teamLabel="경기고" monogram="GG" players={players} />;
}
