"use client";

import { TeamPlayer, TeamRoster } from "./gd-roster";

export const players: TeamPlayer[] = [
  { id: "kd-56", number: "56", name: "강석훈", position: "외야수", grade: "1학년", height: 180, weight: 70, batsThrows: "우투좌타" },
  { id: "kd-38", number: "38", name: "강장호", position: "투수", grade: "2학년", height: 185, weight: 85, batsThrows: "우투우타" },
  { id: "kd-15", number: "15", name: "고대영", position: "투수", grade: "3학년", height: 184, weight: 83, batsThrows: "우투우타" },
  { id: "kd-27", number: "27", name: "곽민준", position: "포수", grade: "3학년", height: 183, weight: 85, batsThrows: "우투우타" },
  { id: "kd-44", number: "44", name: "김담", position: "외야수", grade: "1학년", height: 182, weight: 81, batsThrows: "우투우타" },
  { id: "kd-2", number: "2", name: "김대현", position: "내야수", grade: "1학년", height: 166, weight: 62, batsThrows: "우투우타" },
  { id: "kd-14", number: "14", name: "김민성", position: "내야수", grade: "2학년", height: 176, weight: 77, batsThrows: "우투우타" },
  { id: "kd-17", number: "17", name: "김민준", position: "투수", grade: "3학년", height: 190, weight: 93, batsThrows: "우투우타" },
  { id: "kd-42", number: "42", name: "김범진", position: "투수", grade: "2학년", height: 187, weight: 82, batsThrows: "우투좌타" },
  { id: "kd-23", number: "23", name: "김세진", position: "투수", grade: "2학년", height: 184, weight: 85, batsThrows: "우투우타" },
  { id: "kd-31", number: "31", name: "김시후", position: "투수", grade: "1학년", height: 186, weight: 78, batsThrows: "우투좌타" },
  { id: "kd-6", number: "6", name: "김유빈", position: "내야수", grade: "2학년", height: 178, weight: 75, batsThrows: "우투좌타" },
  { id: "kd-36", number: "36", name: "김준건", position: "내야수", grade: "1학년", height: 175, weight: 80, batsThrows: "우투우타" },
  { id: "kd-29", number: "29", name: "김태양", position: "투수", grade: "3학년", height: 190, weight: 90, batsThrows: "좌투좌타" },
  { id: "kd-13", number: "13", name: "김태훈", position: "투수", grade: "2학년", height: 183, weight: 80, batsThrows: "우투우타" },
  { id: "kd-49", number: "49", name: "김한결", position: "투수", grade: "1학년", height: 183, weight: 76, batsThrows: "우투우타" },
  { id: "kd-51", number: "51", name: "노영현", position: "외야수", grade: "1학년", height: 174, weight: 68, batsThrows: "우투좌타" },
  { id: "kd-57", number: "57", name: "사효찬", position: "외야수", grade: "3학년", height: 183, weight: 78, batsThrows: "좌투좌타" },
  { id: "kd-37", number: "37", name: "송재훈", position: "투수", grade: "학년 미확인", height: 184, weight: 80, batsThrows: "우투우타" },
  { id: "kd-30", number: "30", name: "신석원", position: "투수", grade: "1학년", height: 182, weight: 80, batsThrows: "우투우타" },
  { id: "kd-32", number: "32", name: "심제왕", position: "내야수", grade: "1학년", height: 179, weight: 80, batsThrows: "우투우타" },
  { id: "kd-16", number: "16", name: "심현우", position: "내야수", grade: "3학년", height: 178, weight: 75, batsThrows: "우투우타" },
  { id: "kd-18", number: "18", name: "안윤재", position: "투수", grade: "3학년", height: 195, weight: 105, batsThrows: "우투우타" },
  { id: "kd-22", number: "22", name: "안준서", position: "포수", grade: "1학년", height: 175, weight: 85, batsThrows: "우투우타" },
  { id: "kd-25", number: "25", name: "양준서", position: "내야수", grade: "1학년", height: 175, weight: 70, batsThrows: "우투우타" },
  { id: "kd-48", number: "48", name: "어지율", position: "투수", grade: "1학년", height: 178, weight: 56, batsThrows: "우투좌타" },
  { id: "kd-63", number: "63", name: "오혜성", position: "외야수", grade: "1학년", height: 181, weight: 72, batsThrows: "우투좌타" },
  { id: "kd-1", number: "1", name: "용석민", position: "투수", grade: "3학년", height: 185, weight: 77, batsThrows: "좌투좌타" },
  { id: "kd-19", number: "19", name: "우성오", position: "투수", grade: "3학년", height: 184, weight: 84, batsThrows: "우투우타" },
  { id: "kd-39", number: "39", name: "유경민", position: "투수", grade: "2학년", height: 180, weight: 83, batsThrows: "우투우타" },
  { id: "kd-24", number: "24", name: "유현수", position: "외야수", grade: "2학년", height: 175, weight: 74, batsThrows: "우투좌타" },
  { id: "kd-9", number: "9", name: "윤도현", position: "투수", grade: "1학년", height: 183, weight: 85, batsThrows: "우투우타" },
  { id: "kd-35", number: "35", name: "이건명", position: "내야수", grade: "1학년", height: 178, weight: 76, batsThrows: "우투우타" },
  { id: "kd-50", number: "50", name: "이건우", position: "외야수", grade: "1학년", height: 183, weight: 74, batsThrows: "우투우타" },
  { id: "kd-55", number: "55", name: "이동경", position: "투수", grade: "1학년", height: 184, weight: 88, batsThrows: "우투우타" },
  { id: "kd-10", number: "10", name: "이동우", position: "포수", grade: "2학년", height: 182, weight: 95, batsThrows: "우투우타" },
  { id: "kd-11", number: "11", name: "이주형", position: "투수", grade: "3학년", height: 187, weight: 90, batsThrows: "우투우타" },
  { id: "kd-47", number: "47", name: "이지후", position: "투수", grade: "2학년", height: 174, weight: 73, batsThrows: "좌투좌타" },
  { id: "kd-41", number: "41", name: "이하율", position: "투수", grade: "2학년", height: 186, weight: 88, batsThrows: "우투좌타" },
  { id: "kd-26", number: "26", name: "임태현", position: "투수", grade: "2학년", height: 180, weight: 85, batsThrows: "우투우타" },
  { id: "kd-40", number: "40", name: "장태민", position: "투수", grade: "1학년", height: 190, weight: 85, batsThrows: "우투우타" },
  { id: "kd-28", number: "28", name: "정명윤", position: "투수", grade: "2학년", height: 183, weight: 90, batsThrows: "우투우타" },
  { id: "kd-7", number: "7", name: "정명훈", position: "내야수", grade: "3학년", height: 178, weight: 80, batsThrows: "우투우타" },
  { id: "kd-34", number: "34", name: "정민찬", position: "투수", grade: "1학년", height: 181, weight: 78, batsThrows: "우투우타" },
  { id: "kd-4", number: "4", name: "정승우", position: "내야수", grade: "1학년", height: 167, weight: 58, batsThrows: "우투우타" },
  { id: "kd-20", number: "20", name: "정유찬", position: "투수", grade: "1학년", height: 187, weight: 92, batsThrows: "우투우타" },
  { id: "kd-61", number: "61", name: "한성민", position: "투수", grade: "2학년", height: 189, weight: 95, batsThrows: "좌투좌타" },
  { id: "kd-33", number: "33", name: "한재준", position: "투수", grade: "2학년", height: 185, weight: 78, batsThrows: "좌투좌타" },
  { id: "kd-54", number: "54", name: "현민호", position: "투수", grade: "1학년", height: 182, weight: 76, batsThrows: "좌투좌타" },
  { id: "kd-21", number: "21", name: "홍예성", position: "투수", grade: "1학년", height: 184, weight: 86, batsThrows: "좌투좌타" },
  { id: "kd-53", number: "53", name: "홍준범", position: "외야수", grade: "3학년", height: 174, weight: 75, batsThrows: "우투우타" },
  { id: "kd-hongjiwoo", number: "—", name: "홍지우", position: "내야수", grade: "2학년", height: 175, weight: 70, batsThrows: "우투우타" },
  { id: "kd-12", number: "12", name: "황유석", position: "투수", grade: "2학년", height: 178, weight: 77, batsThrows: "우투우타" },
  { id: "kd-52", number: "52", name: "황재욱", position: "외야수", grade: "3학년", height: 183, weight: 83, batsThrows: "우투좌타" },
  { id: "kd-3", number: "3", name: "황태훈", position: "내야수", grade: "2학년", height: 182, weight: 74, batsThrows: "우투좌타" },
];

export default function KyungdongRoster() {
  return <TeamRoster sectionId="kyungdong-roster" kicker="KYUNGDONG HIGH SCHOOL · U-18" title="경동고 선수단" subtitle="2026 등록 선수 55명 · 감독 조정권" teamLabel="경동고" monogram="KD" players={players} />;
}
